# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Place.create([
  { :name => nil, :desc => nil, :street => nil, :city => nil, :state => nil, :zip => nil, :user_id => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



User.create([
  { :created_at => "2012-11-15 02:59:49", :updated_at => "2012-11-15 03:11:24", :provider => "foam_auth", :uid => nil, :name => "Foamy McFoamerson", :email => "foamy@gmail.com", :token => nil, :token_expires_at => nil, :refresh_token => nil }
], :without_protection => true )


